import type { Friend } from "../model/types";

export const MOCK_FRIENDS: Friend[] = [
  {
    id: "u-minh",
    name: "Minh Bia",
    occupation: "Sales",
    alcoholToleranceLevel: "LEVEL_2",
    relation: "both",
    sessionsTogether: 8,
    lastSessionAt: new Date(Date.now() - 3 * 86400_000).toISOString(),
    bio: "Networking nhẹ, đúng hẹn.",
  },
  {
    id: "u-lan",
    name: "Lan Chill",
    occupation: "Designer",
    alcoholToleranceLevel: "LEVEL_1",
    relation: "drinking_buddy",
    sessionsTogether: 5,
    lastSessionAt: new Date(Date.now() - 7 * 86400_000).toISOString(),
    bio: "Tâm sự nhẹ nhàng, không ép uống.",
  },
  {
    id: "u-ha",
    name: "Hà Networking",
    occupation: "HR",
    alcoholToleranceLevel: "LEVEL_2",
    relation: "friend",
    sessionsTogether: 3,
    lastSessionAt: new Date(Date.now() - 14 * 86400_000).toISOString(),
  },
  {
    id: "u-huy",
    name: "Huy Chiến",
    occupation: "Engineer",
    alcoholToleranceLevel: "LEVEL_3",
    relation: "both",
    sessionsTogether: 6,
    lastSessionAt: new Date(Date.now() - 2 * 86400_000).toISOString(),
  },
  {
    id: "u-duc",
    name: "Đức Tài",
    occupation: "Teacher",
    alcoholToleranceLevel: "LEVEL_1",
    relation: "drinking_buddy",
    sessionsTogether: 4,
    lastSessionAt: new Date(Date.now() - 21 * 86400_000).toISOString(),
  },
  {
    id: "u-vy",
    name: "Vy Vui Vẻ",
    occupation: "Marketer",
    alcoholToleranceLevel: "LEVEL_3",
    relation: "friend",
    sessionsTogether: 2,
    lastSessionAt: new Date(Date.now() - 30 * 86400_000).toISOString(),
  },
];
